### PR TITLE
Make clammy gevent-safe

### PR DESCRIPTION
**Pull request by stringfellow**
Changes brought in from https://github.com/graingert/python-clamd/pull/23

- use sendall() instead of send()
- allow custom max_buffer_size
- set socket timeout before connect

Thanks to @mrname

### CODE REVIEW

**Comment by DanMauger** [comment]
:+1: - much appreciated all around!

**Comment by nilstoedtmann** [comment]
Without @mrname's patch https://github.com/graingert/python-clamd/pull/23 , python-clamd/clammy seem to not be gevent-safe. Would be great to see Justin's fix applied.

**Comment by stringfellow** [comment]
*bump* @ranguli - please can someone take a look at this?

**Comment by ranguli** [comment]
Hey @stringfellow, thanks for the PR and for following up - no idea why I didn't see any of these notifications when they came through in May. I'll review and merge :+1:

**Comment by ranguli** [comment]
Will try and get a new release out soon. Thanks! :rocket:

**Comment by ranguli** [comment]
Release is now available here and on Pip. https://github.com/ranguli/clammy/releases/tag/v1.0.0

**Comment by stringfellow** [comment]
Thanks @ranguli ! :) Happy new year!

**Pull request merged**
